### ISSUE TITLE
Feature request: filter output by node role or other labels

### ISSUE THREAD

**Issue by luispollo** [etopeter/kubectl-view-utilization#13]
Thanks for contributing this, it's super useful! 

It would be nice to be able to get output filtered by node role (label "kubernetes.io/role=node"), or maybe arbitrary labels. Generally we don't run a lot of stuff on our masters, for example, so I'm more interested in seeing just the utilization on worker nodes.

Thoughts?

**Comment by etopeter** [comment]
That's great idea. 
I was also thinking to add nodes sub-command just like namespaces in the future. This could show more detailed info. This information largely available in kubectl describe node command.

Example:
```kubectl view-utilization nodes
NAME                         ROLE        CPU    MEMORY
10-0-0-50-us-west-2.local    worker      2      4.2 Gi
10-0-0-51-us-west-2.local    masetr      1.5    512 Mi
10-0-0-52-us-west-2.local    worker      4      3.5 Gi
```

```kubectl view-utilization nodes -l kubernetes.io/role=worker
NAME                         ROLES        CPU    MEMORY
10-0-0-50-us-west-2.local    worker      2      4.2 Gi
10-0-0-52-us-west-2.local    worker      4      3.5 Gi
```

But to your point maybe more value would give simple aggregation of those values. Example run without sub-command but with label filter:

```
kubectl view-utilization -l kubernetes.io/role=worker                     
cores      2.3 / 8       (28%)
memory  1.2GiB / 30GiB   (4%)
```

or make it easy with `-r --role flag`
```
kubectl view-utilization --role worker                     
cores      2.3 / 8       (28%)
memory  1.2GiB / 30GiB   (4%)```

Since list of all nodes is fairly simple to get with kubectl describe and grep maybe more value would give  just summarized version.

**Comment by etopeter** [comment]
This feature is implemented now. Please share if you have any feedback otherwise we can close this issue.

**Comment by luispollo** [comment]
Works great, thank you! Closing the issue.
