### ISSUE TITLE
"Context error" when passing --context that is the current context

### ISSUE THREAD

**Issue by 2rs2ts** [etopeter/kubectl-view-utilization#55]
**Describe the bug**

When current context is `foo` and you pass `--context foo` to this plugin it returns `Context error`. Why would I do that you ask, well it is handy to loop over all contexts with `kubectx` like this: `for ctx in $(kubectx) ; do kubectl view-utilization --context $ctx -h ; done`.

**System details**
- Operating system that client is running: Debian buster:
- kubectl client and server version `kubectl version`: 1.17.8
- view-utilization plugin version `kubectl view-utilization -v`: v0.3.2

**Comment by etopeter** [comment]
Thank you for reporting this bug. Looks like there is error when checking if context exists function.
https://github.com/etopeter/kubectl-view-utilization/blob/master/kubectl-view-utilization#L146
```
test_kubectl_context() {
    local output

    # Check if context exists in kubeconfig
    output=$(kubectl config get-contexts ${VIEW_UTILIZATION_CONTEXT} --no-headers | awk '{print $1;}')

    if [ "${output}" == "${VIEW_UTILIZATION_CONTEXT}" ]; then
        context="--context=${VIEW_UTILIZATION_CONTEXT}"
    else
        echo "Context error"
        exit 1
    fi
}
```

Fix for that should be simple.

**Comment by etopeter** [comment]
This issue should be fixed by the latest fix. Would you be able to verify this fix against master branch?

You can copy kubectl-view-utilization from master branch (chmod +x kubectl-view-utilization) and execute in current derectory ./kubectl-view-utilization instead using command `kubectl view-utilization`

Effectively in order to test your for loop command would looks like this 
`for ctx in $(kubectx) ; do ./kubectl-view-utilization --context $ctx -h ; done`

**Comment by 2rs2ts** [comment]
I can confirm your fix works. Thanks for the quick patch!
